/** Media item to attach to a post. */
export interface PublishMedia {
  /** Public URL of the media file. */
  url: string;
  /** Media type. */
  type: 'image' | 'video';
  /** Accessible description (optional). */
  alt_text?: string;
}

/** Pre-fill passed to widget.publish(). */
export interface PublishPreFill {
  /** Caption / body text for the post. */
  caption?: string;
  /** Media attachments to display (read-only) in each account accordion. */
  media?: PublishMedia[];
}

/** Config passed to PalactixWidget.init(). */
export interface PublisherConfig {
  /**
   * Short-lived signed init token generated by your server via
   * POST /widget/tokens (with Authorization: Basic base64(widgetId:secret)).
   */
  token: string;
  /**
   * Override the publisher app URL. For local development only.
   * Defaults to production URL.
   * @example "http://localhost:3001"
   */
  appUrl?: string;
  /**
   * Override the widget's primary accent color.
   * @example "#e11d48"
   */
  primary?: string;
  /**
   * How the widget is presented.
   * - `"modal"`  — centred dialog (default).
   * - `"drawer"` — slide-in panel from the right.
   * @default "modal"
   */
  mode?: 'modal' | 'drawer';
  /** Called when the widget iframe is fully initialised and ready. */
  onReady?: () => void;
  /** Called when the user dismisses the widget panel. */
  onClose?: () => void;
  /**
   * Called after the widget successfully publishes.
   * Receives the publish result data.
   */
  onPublished?: (post: unknown) => void;
}

/** Returned by PalactixWidget.init(). */
export interface PublisherWidget {
  /**
   * Open the publisher panel, optionally pre-filling caption and media.
   * Call this from your own button's click handler.
   */
  publish(preFill?: PublishPreFill): void;
  /** Destroy the widget and remove all DOM nodes. */
  destroy(): void;
}

/** The global PalactixWidget object attached to window. */
export interface PalactixWidgetGlobal {
  /**
   * Load the publisher widget. Returns an instance with a publish() method.
   * Call this once on page load — the iframe is pre-loaded in the background.
   *
   * @example
   * const widget = PalactixWidget.init({ token: serverGeneratedToken });
   * myButton.addEventListener('click', () => {
   *   widget.publish({ caption: 'Hello world!', media: [...] });
   * });
   */
  init(config: PublisherConfig): PublisherWidget;
}

declare global {
  interface Window {
    PalactixWidget: PalactixWidgetGlobal;
  }
}
